application: how-you-been
version: 0-2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: whence.app

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest
#- name: MarkupSafe
#  version: latest
